# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-31 01:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Configurator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='parent',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Configurator.Equipment'),
        ),
    ]
