# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-31 01:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Configurator', '0002_auto_20200831_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='equipment',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Configurator.Equipment'),
        ),
    ]
