# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-31 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configurator', '0005_auto_20200831_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='layout',
            field=models.TextField(null=True),
        ),
    ]
